services:
  app:
    image: ${APP_IMAGE:-showcase-frontend:latest}
    restart: always
    ports:
      - "3011:3011"
    networks:
      - showcase-frontend-network

networks:
  showcase-frontend-network:
    external: true
