services:
  app:
    image: ${APP_IMAGE:-ai-feature-showcase:latest}
    restart: always
    ports:
      - "3011:3011"
    networks:
      - ai-showcase-network

networks:
  ai-showcase-network:
    external: true
