import type { FeatureMeta } from "@/types/feature";

export const features: FeatureMeta[] = [
  {
    slug: "text-summarization",
    name: "Text Summarization",
    category: "NLP",
    description: "Condense long documents into clear, concise summaries in seconds.",
    badge: "Stable",
    icon: "📝",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Artificial_Intelligence_%26_AI_%26_Machine_Learning_-_30212411048.jpg/1280px-Artificial_Intelligence_%26_AI_%26_Machine_Learning_-_30212411048.jpg",
    features: [
      "Summarize documents up to 100,000 tokens in a single request.",
      "Supports multiple output formats: bullet points, paragraphs, and key insights.",
      "Multilingual support across 30+ languages.",
      "Adjustable summary length from one sentence to several paragraphs.",
    ],
  },
  {
    slug: "sentiment-analysis",
    name: "Sentiment Analysis",
    category: "NLP",
    description: "Detect emotions and opinions in text with high accuracy across multiple languages.",
    badge: "Stable",
    icon: "💬",
    imageUrl: "https://trendsresearch.org/wp-content/uploads/2025/06/AI-and-the-Gig-Economy-How-AI-is-Reshaping-Freelance-and-Contract-Work.jpg",
    features: [
      "Classifies sentiment as positive, negative, neutral, or mixed.",
      "Fine-grained emotion detection: joy, anger, fear, surprise, and more.",
      "Aspect-based sentiment for structured feedback analysis.",
      "Batch processing for high-volume text streams.",
    ],
  },
  {
    slug: "image-analysis",
    name: "Image Analysis",
    category: "Vision",
    description: "Understand, label, and extract structured data from any image automatically.",
    badge: "Beta",
    icon: "🖼️",
    imageUrl: "https://ric.edu.pk/wp-content/uploads/2025/01/Artificial-Intelligence-1.jpg",
    features: [
      "Auto-generate descriptive captions for any image.",
      "Detect and classify objects, scenes, and activities.",
      "Extract text from images with OCR precision.",
      "Return structured JSON output for downstream processing.",
    ],
  },
  {
    slug: "object-detection",
    name: "Object Detection",
    category: "Vision",
    description: "Identify and locate multiple objects in images with bounding box precision.",
    badge: "Beta",
    icon: "🔍",
    imageUrl: "https://vidyaenews.most.gov.lk/wp-content/uploads/2025/09/1727771640461-780x470-1.png",
    features: [
      "Detects 1,000+ object classes out of the box.",
      "Returns bounding box coordinates with confidence scores.",
      "Real-time inference optimized for edge deployment.",
      "Custom model fine-tuning via few-shot labeling.",
    ],
  },
  {
    slug: "speech-to-text",
    name: "Speech to Text",
    category: "Audio",
    description: "Transcribe spoken audio to text with speaker diarization and timestamp support.",
    badge: "Stable",
    icon: "🎙️",
    imageUrl: "https://cdn.nishtyainfotech.com/content/learnings/data/blog/banner/69a6bd93572ac8.59468835.webp",
    features: [
      "Transcription accuracy of 95%+ across 60 languages.",
      "Speaker diarization to distinguish multiple speakers.",
      "Word-level timestamps for caption generation.",
      "Noise-robust model handles real-world audio conditions.",
    ],
  },
  {
    slug: "text-to-speech",
    name: "Text to Speech",
    category: "Audio",
    description: "Convert text into natural-sounding speech across dozens of voices and languages.",
    badge: "New",
    icon: "🔊",
    imageUrl: "https://www.neilsahota.com/wp-content/uploads/2022/09/What-is-AI-how-does-it-work.jpg",
    features: [
      "50+ voices covering 20 languages and regional accents.",
      "SSML support for fine-grained prosody control.",
      "Streaming output for low-latency real-time playback.",
      "Custom voice cloning from as little as 30 seconds of audio.",
    ],
  },
  {
    slug: "data-extraction",
    name: "Data Extraction",
    category: "Data",
    description: "Pull structured data from unstructured sources like PDFs, emails, and web pages.",
    badge: "Stable",
    icon: "📊",
    imageUrl: "https://chrysalishigh.com/wp-content/uploads/2026/01/artificial-intelligence-vs-human-intelligence-1024x683.png",
    features: [
      "Extracts tables, key-value pairs, and entities from PDFs.",
      "Supports scanned documents via integrated OCR.",
      "Output schema is fully configurable via JSON.",
      "Handles invoices, contracts, and forms out of the box.",
    ],
  },
  {
    slug: "code-generation",
    name: "Code Generation",
    category: "Coding",
    description: "Generate production-ready code snippets from natural language descriptions.",
    badge: "New",
    icon: "💻",
    imageUrl: "https://storage.googleapis.com/techsauce-prod/ugc/uploads/2024/11/1732008676_Aiag_800_%281%29.jpg",
    features: [
      "Supports 30+ programming languages including TypeScript, Python, and Go.",
      "Generates unit tests alongside implementation code.",
      "Context-aware completions using your existing codebase.",
      "Explains generated code in plain language on request.",
    ],
  },
  {
    slug: "document-qa",
    name: "Document Q&A",
    category: "Multimodal",
    description: "Ask questions about any document and get precise, cited answers instantly.",
    badge: "Beta",
    icon: "📄",
    imageUrl: "https://blogs.cisco.com/gcs/ciscoblogs/1/2024/07/AI_blog.png",
    features: [
      "Answers grounded in source text with inline citations.",
      "Supports PDF, DOCX, TXT, and web URLs as input.",
      "Multi-document querying across an entire knowledge base.",
      "Conversational follow-up within the same document context.",
    ],
  },
];

export const featuredFeatures = features.filter((f) => !f.disabled);
